name 'home-lab'
maintainer 'Nathan Williams'
maintainer_email 'nath.e.will@gmail.com'
license 'apache2'
description 'Installs/Configures home-lab'
long_description 'Installs/Configures home-lab'
version '0.1.0'

depends 'systemd', '~> 1.0'
depends 'ntp', '~> 1.8'
depends 'sudo', '~> 2.7'
depends 'postfix', '~> 3.7'
depends 'openssh', '~> 1.5'
depends 'firewall', '~> 2.1'
